# @package _global_

fps: 20

env:
  name: mimicgen
  task: CoffeePreparation_D1
  state_dim: 9
  action_dim: 7
  episode_length: 850
  meta: coffee_preparation_d1_env.json
  image_keys:
  - agentview
  - robot0_eye_in_hand
  state_keys:
  - robot0_eef_pos
  - robot0_eef_quat
  - robot0_gripper_qpos

  use_delta_action: true
